In [24]:
import numpy as np

A = np.array([[3,6]])
B = np.array([[5], [2]])

#A
print(A.dot(B))
print("----")

A = np.array([[3,6]])
B = np.array([[5], [2]])
#B
print(B.dot(A))
print("----")
#C

A = np.array([[5],[2]])
B = np.array([[3], [6]])
#print(A.dot(B))
print("----")


#D
A = np.array([[1,2],[3,5]])
B = np.array([[4],[6]])

#print(np.dot(A,B))
print("----")


#E
C = np.array([[4],[6]])
D = np.array([[1,2], [3,5]])

#print(C.dot(D))
print("----")

C = np.array([[4],[6]])
D = np.array([[1,2], [3,5]])



#F
C = np.array([[4],[6]])
D = np.array([[1,2], [3,5]])

print(C.dot(D))
print("----")




[[27]]
----
[[15 30]
 [ 6 12]]
----
----
----
----


ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [34]:
X = np.array([[1,0],[0,2],[3,0]])
Y = np.array([[0,4],[0,5],[6,0]])

print(X*Y)
print("----")
print(A*B)
print("----")
print(A.dot(B))
print("----")
print(A.dot(B))
print("----")
print(A.dot(B))
print("----")
print(A.dot(B))

[[ 0  0]
 [ 0 10]
 [18  0]]
----
[[ 0  0]
 [ 0 10]
 [18  0]]
----


ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [28]:
A = np.array([[0, -1, 2], [1, 0, 1], [1, 1, 0]])
B = np.array([[-1, 0, 3], [2, 1, 0], [1, 3, -5]])
print(A.shape,B.shape)
print(A.dot(B))

(3, 3) (3, 3)
[[  0   5 -10]
 [  0   3  -2]
 [  1   1   3]]
